# Generated by Django 4.1.6 on 2023-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
