# Generated by Django 4.1.6 on 2023-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0002_alter_comment_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
