# Generated by Django 4.1.6 on 2023-02-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
