# Generated by Django 4.1.6 on 2023-03-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0008_post_heartqty_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heartQty',
        ),
    ]
