# Generated by Django 4.1.6 on 2023-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0009_remove_post_heartqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='heartQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='heartQty',
            field=models.IntegerField(default=0),
        ),
    ]
