# Generated by Django 4.1.6 on 2023-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_alike_app', '0010_comment_heartqty_post_heartqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='heartQty',
        ),
    ]
